// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_-X51R9xjX1weaepDVYNG_sUHwOpW90',
    appId: '1:915581332814:web:d97afdd65ebe59e0c6c21f',
    messagingSenderId: '915581332814',
    projectId: 'anxieease-sensors',
    authDomain: 'anxieease-sensors.firebaseapp.com',
    databaseURL: 'https://anxieease-sensors-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anxieease-sensors.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbb5HgO3hxs8R9DXX9lnj4PAV3XBbAP-E',
    appId: '1:915581332814:android:aedc9b1bc20dc3aac6c21f',
    messagingSenderId: '915581332814',
    projectId: 'anxieease-sensors',
    databaseURL: 'https://anxieease-sensors-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anxieease-sensors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQX3X9CAM4Sq3FrXphtfQejeh-U59QTc',
    appId: '1:915581332814:ios:473c1d0b2d6c2610c6c21f',
    messagingSenderId: '915581332814',
    projectId: 'anxieease-sensors',
    databaseURL: 'https://anxieease-sensors-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anxieease-sensors.firebasestorage.app',
    iosBundleId: 'com.example.ctrlzed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlQX3X9CAM4Sq3FrXphtfQejeh-U59QTc',
    appId: '1:915581332814:ios:473c1d0b2d6c2610c6c21f',
    messagingSenderId: '915581332814',
    projectId: 'anxieease-sensors',
    databaseURL: 'https://anxieease-sensors-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anxieease-sensors.firebasestorage.app',
    iosBundleId: 'com.example.ctrlzed',
  );
}
